### ISSUE TITLE
[Suggest] VitePress 风格的暗黑模式切换

### ISSUE THREAD

**Issue by yjl9903** [YurierDept/get-bonus#40]
请填写您的意见与建议。如果可以，请尽量书写详细。  
Please fill in your comments and suggestions. If possible, please be as detailed as possible.

**Comment by ruaharico** [comment]
补充：目前已经实现了默认跟随系统设置的深浅色切换，以及简单的深浅色切换按钮，但是暂时没有实现更为美观的滑块式按钮，也就是像 VitePress 那样的按钮，
